//
//  File.swift
//  
//
//  Created by Devon Martin on 9/21/23.
//

import Foundation

extension ChatGPT {
	
	static func getRandomPrompt(about topic: String) -> String {
		
		let prompts = [
			"Write a short essay about \(topic).",
			"Tell me five fun facts about \(topic).",
			"Summarize \(topic).",
			"Create a fictional story that revolves around \(topic).",
			"Write a poem about \(topic).",
			"Explain \(topic) like I'm 5 years old.",
			"Explain the pros and cons of \(topic).",
			"Explain the importance of \(topic) in today's world.",
			"Describe the history and development of \(topic).",
			"Imagine a future where \(topic) plays a major role. What would it look like?",
			"How can we apply \(topic) to solve real-world problems?",
			"Analyze the impact of \(topic) on society and the environment.",
			"Discuss the ethical implications of \(topic).",
			"Explain the technological aspects of \(topic).",
			"What are the major challenges and opportunities with \(topic)?",
			"Discuss how \(topic) is affecting global politics.",
			"What does the future hold for \(topic)?",
			"Explain how \(topic) works and why it's important.",
			"What are some potential solutions related to \(topic)?",
			"What are the psychological aspects of \(topic)?",
			"Discuss the impact of \(topic) on the global economy.",
			"What are the latest advancements in \(topic)?",
			"Explain the scientific theory behind \(topic).",
			"How is \(topic) changing the world of healthcare?",
			"What are the philosophical implications of \(topic)?",
			"How does \(topic) influence our day-to-day life?",
			"Discuss the cultural significance of \(topic).",
			"What are the environmental impacts of \(topic)?",
			"How is \(topic) transforming modern education?",
			"Discuss the current trends and future prospects of \(topic).",
			"Explain the role of \(topic) in sustainable development.",
			"How is \(topic) influencing the dynamics of social interaction?",
			"Discuss the future implications of \(topic) in the realm of artificial intelligence.",
			"What is the potential of \(topic) as a future energy source?",
			"How is \(topic) affecting the mental health of the population?",
			"What is the global impact of \(topic) on climate change?",
			"How does \(topic) affect the structure of international relations?",
			"Discuss the application of \(topic) in space exploration."
		]
		
		return prompts.randomElement()!
	}
	
	static func getRandomPrompt() -> String {
		
		let prompts = [
			"What is the current state of quantum computing and its future implications?",
			"Explain the Fermi Paradox and discuss potential solutions to it.",
			"Describe the process of creating a vaccine and why it usually takes so long.",
			"What are the current advancements in renewable energy technologies?",
			"Explain the concept of time dilation in the theory of relativity.",
			"What's the role of artificial intelligence in combating climate change?",
			"What can we learn from the political system of ancient Rome?",
			"How does the human brain interpret music?",
			"Discuss the impact of technology on the job market.",
			"Explain how DNA sequencing works.",
			"What were the primary causes of the fall of the Soviet Union?",
			"What are the ethical implications of gene editing technologies like CRISPR?",
			"What are some potential solutions to overpopulation?",
			"How does machine learning work?",
			"What does 'quantum entanglement' mean, and why is it significant?",
			"Discuss the impacts of deforestation on global climate.",
			"What is the significance of dark matter and dark energy in cosmology?",
			"How is virtual reality changing the entertainment industry?",
			"What is nanotechnology and how is it used today?",
			"What are some theories about the origin of life on Earth?",
			"How do linguists study and classify languages?",
			"Discuss the social and psychological impacts of social media use.",
			"What is string theory?",
			"How do black holes form?",
			"How does the human immune system function?",
			"Discuss the effects of space travel on the human body.",
			"What is the role of the World Health Organization?",
			"What is cognitive bias, and how does it affect our decisions?",
			"What are some of the challenges and opportunities with electric vehicles?",
			"Discuss the future of space exploration and colonization.",
			"Explain the significance of the Turing Test.",
			"What are some of the biggest threats to biodiversity today?",
			"What is the state of cryptocurrency and blockchain technology in 2023?",
			"What are the major factors driving income inequality in the world?",
			"Discuss the principles and implications of Moore's Law.",
			"How does climate change affect wildlife migration patterns?",
			"What are the most effective ways to combat fake news and misinformation online?",
			"What is the Higgs Boson, and why is it called the 'God Particle'?",
			"What are the benefits and drawbacks of globalization?",
			"How does encryption work to protect online privacy?",
			"How is neuroscience helping us understand mental health disorders?",
			"What is the concept of 'universal basic income' and its pros and cons?",
			"What is the status of Mars exploration projects in 2023?",
			"What are the latest developments in 3D printing technology?",
			"Discuss the evolution and impacts of internet culture.",
			"What does the future hold for virtual and augmented reality?",
			"How are machine learning and AI used in healthcare?",
			"Explain how neural networks mimic the human brain.",
			"How did the internet change the dynamics of the global economy?",
			"Discuss the role of cybersecurity in modern warfare.",
			"What were the factors behind the rise of China as a global power?",
			"What are some philosophical implications of AI and consciousness?",
			"Discuss how data science is transforming business decision making.",
			"Explain the concept of 'multiverse' in theoretical physics.",
			"What are the latest advancements in biotechnology?",
			"How is climate change impacting the world's oceans?",
			"Discuss the psychological effects of long-term isolation on humans.",
			"What is the current state of nuclear power and its future prospects?",
			"What is the significance of the human genome project?",
			"Discuss the impacts and challenges of online education.",
			"What is the potential of hydrogen as a future energy source?",
			"How does stress affect the human body and mind?",
			"Discuss the importance and future of net neutrality.",
			"How are AI and robotics changing the manufacturing industry?",
			"What are the advantages and disadvantages of telecommuting?",
			"Discuss the role of art and culture in society.",
			"Explain how language influences the way we think.",
			"What are the societal implications of the 'Big Data' revolution?",
			"Discuss the role and impact of international organizations like the United Nations.",
			"What is the concept of 'technological singularity'?",
			"Discuss the history and significance of the European Union.",
			"How are cryptocurrencies disrupting traditional financial systems?",
			"What is the role of intuition in scientific discovery?",
			"Explain how human consciousness is understood in modern neuroscience.",
			"What are the implications of the melting Arctic ice?",
			"Discuss the latest trends in artificial intelligence research.",
			"What is the role of ethics in AI development?",
			"Explain the impact of the digital revolution on journalism.",
			"How does meditation affect the brain?",
			"Discuss the significance of the discovery of exoplanets.",
			"What is the state of virtual assistants and voice recognition technology in 2023?",
			"What are the major challenges to achieving sustainable agriculture?",
			"Discuss the geopolitical implications of the rise of renewable energy.",
			"How is AI reshaping the retail industry?",
			"What is the role of satellites in modern communication systems?",
			"What is the current status of autonomous vehicles?",
			"Discuss the future of work in the era of automation and AI.",
			"Explain the principles and implications of game theory.",
			"What is the potential of virtual reality in education?",
			"What are the environmental implications of fast fashion?",
			"Discuss the scientific and philosophical aspects of dreams.",
			"What is the impact of antibiotic resistance, and how can we combat it?",
			"How are new technologies changing the face of marketing?",
			"Explain the scientific consensus on climate change.",
			"Discuss the mental health impact of social media usage.",
			"What is the concept of 'hive mind' in the context of collective intelligence?",
			"What are the potential future implications of nanotechnology in medicine?"
		]
		
		return prompts.randomElement()!
	}
}
